[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
dependsOn = ["setup"]
paths = ["backend"]
cmds = [
  "cd backend && npm ci --only=production"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd backend && npx prisma generate"
]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"
